# Generated by Django 5.0.4 on 2024-05-03 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deposer', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('annee', models.CharField(default='2023-2024', max_length=10)),
                ('des', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])])),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateField(auto_created=True)),
                ('contenu', models.CharField(max_length=500)),
                ('Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_created=True)),
                ('nom', models.CharField(max_length=50)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])])),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])])),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.module'),
        ),
        migrations.CreateModel(
            name='Mooc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm', 'avi', 'mkv', 'ogg', 'wmv'])])),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('duree', models.CharField(max_length=20)),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.promo'),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['rar', 'zip'])])),
                ('lien', models.CharField(blank=True, max_length=200, null=True)),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
    ]
