# Generated by Django 5.0.4 on 2024-05-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mooc',
            old_name='durée',
            new_name='duree',
        ),
    ]
