# Generated by Django 5.0.4 on 2024-05-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
