# Generated by Django 5.0.4 on 2024-05-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='des',
        ),
        migrations.AddField(
            model_name='course',
            name='Niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo_app.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='Niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo_app.niveau'),
            preserve_default=False,
        ),
    ]
