# Generated by Django 5.0.4 on 2024-05-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0002_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('Promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.promo')),
            ],
        ),
    ]
