# Generated by Django 5.0.4 on 2024-05-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0002_remove_promo_des_course_niveau_promo_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='nom',
        ),
    ]
