# Generated by Django 5.0.4 on 2024-05-03 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='Module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo_app.module'),
            preserve_default=False,
        ),
    ]
