# Generated by Django 5.0.4 on 2024-05-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0003_remove_mooc_chapitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooc',
            name='Chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre'),
            preserve_default=False,
        ),
    ]
