# Generated by Django 5.0.4 on 2024-05-01 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0004_mooc_chapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooc',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
