# Generated by Django 5.0.4 on 2024-05-02 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0007_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiche_td_tp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf'])])),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
