# Generated by Django 5.0.4 on 2024-05-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0008_fiche_td_tp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fiche_td_tp',
            new_name='Fiche',
        ),
    ]
