# Generated by Django 5.0.4 on 2024-05-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0009_rename_fiche_td_tp_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche',
            name='Chapitre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre'),
            preserve_default=False,
        ),
    ]
