# Generated by Django 5.0.4 on 2024-05-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0011_devoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateField(auto_created=True)),
                ('contenu', models.CharField(max_length=500)),
                ('Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.cours')),
            ],
        ),
    ]
