# Generated by Django 5.0.4 on 2024-05-02 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0012_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf'])])),
                ('lien', models.CharField(max_length=200)),
                ('Chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_app.chapitre')),
            ],
        ),
    ]
