# Generated by Django 5.0.4 on 2024-05-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0013_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='lien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
