# Generated by Django 5.0.4 on 2024-05-02 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0014_alter_ressource_file_alter_ressource_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['rar', 'zip'])]),
        ),
    ]
