# Generated by Django 5.0.4 on 2024-05-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_app', '0015_alter_cours_file_alter_devoir_file_alter_fiche_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='promo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='promo_app.promo'),
            preserve_default=False,
        ),
    ]
